### ISSUE TITLE
Explore adding SNI (Server Name Indication) support

### ISSUE THREAD

**Issue by schmidtw** [Comcast/petasos#27]
If we can add SNI (Server Name Indication) support to petasos, then it will be able to host multiple domains securely without the need of an additional redirection host.

https://stackoverflow.com/questions/35641888/is-it-possible-to-host-multiple-domain-tls-in-golang-with-net-http

**Comment by kcajmagic** [comment]
This has been merged into [webpa_common](https://github.com/Comcast/webpa-common/pull/350). Unfortunately the [parodus](https://github.com/Comcast/parodus) client can't handle SNI
